import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Footer } from "./components/organisms/Footer/Footer";

import { Navbar } from "@/app/components/organisms/Navbar/Navbar"
import { MovilNavbar } from "@/app/components/organisms/Navbar/MovilNavbar"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth">
      <body className="font-sans antialiased">
        <div className="flex min-h-screen flex-col text-foreground">
         
          <header className=" hidden lg:block sticky top-0 z-50">       
            <Navbar />
          </header>

         
          <div className="block lg:hidden">
            <MovilNavbar />
          </div>

          <main className="flex-1">
            {children}
          </main>

         
        </div>


        {process.env.NODE_ENV === "production" }
      </body>
    </html>

  );
}
